# Generated by Django 4.2.16 on 2026-02-24 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_status', 'Order Status Update'), ('prescription_status', 'Prescription Status Update'), ('consultation_message', 'New Consultation Message'), ('new_consultation', 'New Consultation Request'), ('consultation_status', 'Consultation Status Update'), ('lab_result', 'Lab Result Ready'), ('lab_status', 'Lab Request Status Update'), ('support_update', 'Support Ticket Update'), ('payout_status', 'Payout Status Update'), ('doctor_verified', 'Doctor Profile Verified'), ('consent_request', 'Guardian Consent Request'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
