# Generated by Django 4.2.16 on 2026-03-16 22:51

from django.db import migrations, models
import django.db.models.deletion


def backfill_prescription_foreign_keys(apps, schema_editor):
    CartItem = apps.get_model('orders', 'CartItem')
    OrderItem = apps.get_model('orders', 'OrderItem')
    Prescription = apps.get_model('prescriptions', 'Prescription')
    PrescriptionItem = apps.get_model('prescriptions', 'PrescriptionItem')

    prescription_ids_by_reference = {
        reference: pk
        for pk, reference in Prescription.objects.values_list('pk', 'reference')
    }

    def resolve_prescription_item_id(reference, product_id):
        if not reference:
            return None
        queryset = PrescriptionItem.objects.filter(prescription__reference=reference)
        if product_id:
            product_match = queryset.filter(product_id=product_id).values_list('pk', flat=True).first()
            if product_match:
                return product_match
        return queryset.values_list('pk', flat=True).first()

    for item in CartItem.objects.exclude(prescription_reference__isnull=True).exclude(prescription_reference=''):
        prescription_reference = item.prescription_reference
        prescription_id = prescription_ids_by_reference.get(prescription_reference)
        if prescription_id:
            item.prescription_id = prescription_id
        item.prescription_item_id = resolve_prescription_item_id(prescription_reference, item.product_id)
        item.save(update_fields=['prescription', 'prescription_item'])

    for item in OrderItem.objects.exclude(prescription_reference__isnull=True).exclude(prescription_reference=''):
        prescription_reference = item.prescription_reference
        prescription_id = prescription_ids_by_reference.get(prescription_reference)
        if prescription_id:
            item.prescription_id = prescription_id
        item.prescription_item_id = resolve_prescription_item_id(prescription_reference, item.product_id)
        item.save(update_fields=['prescription', 'prescription_item'])


def reverse_backfill_prescription_foreign_keys(apps, schema_editor):
    CartItem = apps.get_model('orders', 'CartItem')
    OrderItem = apps.get_model('orders', 'OrderItem')

    for model in (CartItem, OrderItem):
        for item in model.objects.exclude(prescription_id=None):
            reference = getattr(item.prescription, 'reference', None)
            if reference and item.prescription_reference != reference:
                item.prescription_reference = reference
                item.save(update_fields=['prescription_reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescription_prescriptio_patient_283c70_idx_and_more'),
        ('orders', '0004_outboundorderpush'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='prescription_id',
            new_name='prescription_reference',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='prescription_id',
            new_name='prescription_reference',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='prescriptions.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='prescriptions.prescriptionitem'),
        ),
        migrations.RunPython(backfill_prescription_foreign_keys, reverse_backfill_prescription_foreign_keys),
        migrations.AlterField(
            model_name='orderevent',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='provider',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paybill', 'M-Pesa Paybill'), ('card', 'Card'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'added_at'], name='orders_cart_cart_id_dd7f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['prescription'], name='orders_cart_prescri_7dd13d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['prescription_item'], name='orders_cart_prescri_53efc4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'created_at'], name='orders_orde_payment_2d60e5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_974e12_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['event_type', '-created_at'], name='orders_orde_event_t_c91115_idx'),
        ),
        migrations.AddIndex(
            model_name='ordernote',
            index=models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_acd406_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['order', 'status'], name='orders_paym_order_i_185426_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider', 'status'], name='orders_paym_provide_dc25f3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['checkout_request_id'], name='orders_paym_checkou_9ba417_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['external_reference'], name='orders_paym_externa_3535be_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['customer', 'status'], name='orders_retu_custome_8e726a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='orders_retu_order_i_62acda_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['is_active', 'sort_order'], name='orders_ship_is_acti_b232fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(
                check=models.Q(user__isnull=False) | models.Q(session_key__isnull=False),
                name='cart_requires_user_or_session',
            ),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'product_variant', 'prescription', 'prescription_item'), name='unique_cart_item_product_variant_prescription'),
        ),
    ]
