# Generated by Django 4.2.16 on 2026-03-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flutterwave_tx_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='flutterwave_tx_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['flutterwave_tx_ref'], name='orders_orde_flutter_8dc2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['flutterwave_tx_id'], name='orders_orde_flutter_394080_idx'),
        ),
    ]
