# Generated by Django 4.2.16 on 2026-03-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_flutterwave_tx_id_order_flutterwave_tx_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='allocated_backorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='allocated_branch_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='allocated_warehouse_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
