# Generated by Django 4.2.16 on 2026-03-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_allocated_backorder_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_item_product_variant_prescription',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_variant',
            new_name='variant',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_variant',
            new_name='variant',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant', 'prescription', 'prescription_item'), name='unique_cart_item_variant_prescription'),
        ),
    ]
