# Generated by Django 4.2.16 on 2026-07-03 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_variant_only_cart_and_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='otc_screening',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='otc_screening',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='disposal_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='inventory_disposition',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='non_resale_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='returned_medicine_quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeliveryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('packed', 'Packed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('failed', 'Delivery failed'), ('returned', 'Returned to pharmacy')], max_length=20)),
                ('courier_name', models.CharField(blank=True, max_length=160)),
                ('courier_phone', models.CharField(blank=True, max_length=50)),
                ('tracking_reference', models.CharField(blank=True, max_length=120)),
                ('recipient_name', models.CharField(blank=True, max_length=160)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('recipient_verified', models.BooleanField(default=False)),
                ('package_condition', models.CharField(blank=True, max_length=160)),
                ('temperature_sensitive', models.BooleanField(default=False)),
                ('temperature_reading_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cold_chain_intact', models.BooleanField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_audits', to='orders.order')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_delivery_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['order', '-recorded_at'], name='orders_deli_order_i_73e6dc_idx'), models.Index(fields=['event_type', '-recorded_at'], name='orders_deli_event_t_09b7fa_idx')],
            },
        ),
    ]
