# Generated by Django 4.2.16 on 2026-07-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cartitem_otc_screening_orderitem_otc_screening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
