# Generated by Django 4.2.16 on 2026-03-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_banner_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(default='home_hero', max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_backorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='max_backorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_stackable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='minimum_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'created_at'], name='products_pr_is_acti_defdf1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='products_pr_brand_i_8f789e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_source', 'is_active'], name='products_pr_stock_s_ec4fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='products_pr_status_515ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['scope', 'status'], name='products_pr_scope_8a4ccc_idx'),
        ),
    ]
