# Generated by Django 4.2.16 on 2026-03-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cmsblock_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500mg, 10mg/5ml, 2%', max_length=50),
        ),
    ]
