# Generated by Django 4.2.16 on 2026-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_subcategory_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='health_concerns',
            field=models.ManyToManyField(blank=True, related_name='brands', to='products.healthconcern'),
        ),
        migrations.AddField(
            model_name='product',
            name='health_concerns',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.healthconcern'),
        ),
    ]
