# Generated by Django 4.2.16 on 2026-03-11 17:51

from django.db import migrations, models
import django.db.models.deletion


def backfill_product_inventory(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductInventory = apps.get_model('products', 'ProductInventory')

    ProductInventory.objects.bulk_create([
        ProductInventory(
            product_id=product.id,
            stock_source=product.stock_source,
            stock_quantity=product.stock_quantity,
            low_stock_threshold=product.low_stock_threshold,
            allow_backorder=product.allow_backorder,
            max_backorder_quantity=product.max_backorder_quantity,
        )
        for product in Product.objects.all().iterator()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_brand_health_concerns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
                ('stock_source', models.CharField(choices=[('branch', 'In Branch'), ('warehouse', 'In Warehouse'), ('out', 'Out of Stock')], default='branch', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('max_backorder_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.RunPython(backfill_product_inventory, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_stock_s_ec4fa6_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='allow_backorder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_backorder_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_source',
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['stock_source'], name='products_pr_stock_s_385782_idx'),
        ),
    ]
