# Generated by Django 4.2.16 on 2026-03-11 18:32

from django.db import migrations, models
import django.db.models.deletion


def split_product_inventory_locations(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductInventory = apps.get_model('products', 'ProductInventory')

    existing_rows = list(ProductInventory.objects.all().iterator())
    seen_locations = set()

    for inventory in existing_rows:
        location = inventory.stock_source if inventory.stock_source in {'branch', 'warehouse'} else 'branch'
        inventory.location = location
        inventory.save(update_fields=['location'])
        seen_locations.add((inventory.product_id, location))

    missing_rows = []
    for product_id in Product.objects.values_list('id', flat=True).iterator():
        for location in ('branch', 'warehouse'):
            if (product_id, location) in seen_locations:
                continue
            missing_rows.append(
                ProductInventory(
                    product_id=product_id,
                    location=location,
                    stock_quantity=0,
                    low_stock_threshold=5 if location == 'branch' else 0,
                    allow_backorder=False,
                    max_backorder_quantity=0,
                )
            )

    if missing_rows:
        ProductInventory.objects.bulk_create(missing_rows)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('products', '0014_productinventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'ordering': ['product_id', 'location']},
        ),
        migrations.AddField(
            model_name='productinventory',
            name='location',
            field=models.CharField(choices=[('branch', 'In Branch'), ('warehouse', 'In Warehouse')], default='branch', max_length=20),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product'),
        ),
        migrations.RunPython(split_product_inventory_locations, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='productinventory',
            name='products_pr_stock_s_385782_idx',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='stock_source',
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['location'], name='products_pr_locatio_e8499f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.UniqueConstraint(fields=('product', 'location'), name='unique_product_inventory_location'),
        ),
    ]
