# Generated by Django 4.2.16 on 2026-03-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productinventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='is_pos_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='location',
            field=models.CharField(choices=[('branch', 'Main Shop'), ('warehouse', 'POS Store')], default='branch', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_source',
            field=models.CharField(choices=[('branch', 'Main Shop'), ('warehouse', 'POS Store'), ('out', 'Out of Stock')], default='branch', max_length=20),
        ),
    ]
