# Generated by Django 4.2.16 on 2026-03-16 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text


def backfill_unified_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    ProductCategory = apps.get_model('products', 'ProductCategory')
    ProductSubcategory = apps.get_model('products', 'ProductSubcategory')

    root_map = {}
    for legacy_root in ProductCategory.objects.all():
        root = Category.objects.filter(slug=legacy_root.slug).first()
        if root is None:
            root = Category.objects.create(
                name=legacy_root.name,
                slug=legacy_root.slug,
                parent=None,
                image=legacy_root.image,
                description=legacy_root.description,
                icon=legacy_root.icon,
                is_active=legacy_root.is_active,
            )
        else:
            updated_fields = []
            for field_name in ('name', 'description', 'icon', 'is_active'):
                source_value = getattr(legacy_root, field_name)
                if getattr(root, field_name) != source_value:
                    setattr(root, field_name, source_value)
                    updated_fields.append(field_name)
            if legacy_root.image and root.image != legacy_root.image:
                root.image = legacy_root.image
                updated_fields.append('image')
            if updated_fields:
                root.save(update_fields=updated_fields)
        root_map[legacy_root.pk] = root

    for legacy_subcategory in ProductSubcategory.objects.select_related('category'):
        root = root_map.get(legacy_subcategory.category_id)
        if root is None:
            continue
        child = Category.objects.filter(parent=root, slug=legacy_subcategory.slug).first()
        if child is None:
            child = Category.objects.create(
                name=legacy_subcategory.name,
                slug=legacy_subcategory.slug,
                parent=root,
                description=legacy_subcategory.description,
                is_active=legacy_subcategory.is_active,
            )
        else:
            updated_fields = []
            for field_name in ('name', 'description', 'is_active'):
                source_value = getattr(legacy_subcategory, field_name)
                if getattr(child, field_name) != source_value:
                    setattr(child, field_name, source_value)
                    updated_fields.append(field_name)
            if updated_fields:
                child.save(update_fields=updated_fields)
        if legacy_subcategory.category_node_id != child.id:
            legacy_subcategory.category_node_id = child.id
            legacy_subcategory.save(update_fields=['category_node'])

    legacy_subcategories = {item.pk: item for item in ProductSubcategory.objects.all()}
    for product in Product.objects.all():
        updated_fields = []
        legacy_subcategory = legacy_subcategories.get(product.subcategory_id)
        if legacy_subcategory and legacy_subcategory.category_node_id:
            if product.catalog_subcategory_id != legacy_subcategory.category_node_id:
                product.catalog_subcategory_id = legacy_subcategory.category_node_id
                updated_fields.append('catalog_subcategory')
            category_node = Category.objects.filter(pk=legacy_subcategory.category_node_id).select_related('parent').first()
            if category_node and category_node.parent_id and product.category_id != category_node.parent_id:
                product.category_id = category_node.parent_id
                updated_fields.append('category')
        if updated_fields:
            product.save(update_fields=updated_fields)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('products', '0021_disable_promotion_stacking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_ci',
        ),
        migrations.AlterUniqueTogether(
            name='productsubcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_subcategory', to='products.category'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='category_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_product_subcategory', to='products.category'),
        ),
        migrations.RunPython(backfill_unified_categories, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'name'], name='products_br_is_acti_bb61bc_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='products_ca_parent__1cafc9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'name'], name='products_ca_is_acti_5a5180_idx'),
        ),
        migrations.AddIndex(
            model_name='healthconcern',
            index=models.Index(fields=['is_active', 'name'], name='products_he_is_acti_6241d4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog_subcategory', 'is_active'], name='products_pr_catalog_439756_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['requires_prescription', 'is_active'], name='products_pr_require_ad0b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='products_pr_is_feat_a1ecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active', 'name'], name='products_pr_is_acti_769b17_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_6c0e7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=django.db.models.query_utils.Q(('parent__isnull', True)), name='unique_root_category_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.comparison.Coalesce('parent', django.db.models.expressions.Value(0)), condition=django.db.models.query_utils.Q(('parent__isnull', False)), name='unique_category_name_per_parent_ci'),
        ),
        migrations.AddConstraint(
            model_name='productsubcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='unique_product_subcategory_name_per_category_ci'),
        ),
    ]
