# Generated by Django 4.2.16 on 2026-03-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_category_unique_category_name_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthconcern',
            name='image',
            field=models.ImageField(blank=True, upload_to='health_concerns/'),
        ),
    ]
