# Generated by Django 4.2.16 on 2026-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_add_product_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage_frequency',
            field=models.CharField(blank=True, help_text='e.g. once_daily, twice_daily', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_notes',
            field=models.CharField(blank=True, help_text='e.g. with food, before meals', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_quantity',
            field=models.CharField(blank=True, help_text='e.g. 1, 2, 1-2', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_unit',
            field=models.CharField(blank=True, help_text='e.g. tablet, capsule, ml, drop', max_length=30),
        ),
    ]
