# Generated by Django 4.2.16 on 2026-03-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_add_dosage_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
