# Generated by Django 4.2.16 on 2026-03-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_increase_subcategory_slug_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_feat_a1ecf6_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.DeleteModel(
            name='ProductBadge',
        ),
    ]
