# Generated by Django 4.2.16 on 2026-03-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_add_pos_link_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='next_restock_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('pos_sync', 'POS Sync'), ('webhook', 'Webhook'), ('order', 'Order'), ('system', 'System')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['source', '-created_at'], name='products_st_source_a555ef_idx'),
        ),
    ]
