# Generated by Django 4.2.16 on 2026-03-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_productvariant_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dosage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500mg, 10mg/5ml, 2%', max_length=50),
        ),
    ]
