# Generated by Django 4.2.16 on 2026-03-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_productvariant_medication_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='warnings',
            field=models.TextField(blank=True),
        ),
    ]
