# Generated by Django 4.2.16 on 2026-03-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_variantinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='product',
        ),
        migrations.RenameIndex(
            model_name='variantinventory',
            new_name='products_va_locatio_e26961_idx',
            old_name='products_va_locatio_b95cce_idx',
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
