# Generated by Django 4.2.16 on 2026-03-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_cartitem_unique_cart_item_product_variant_prescription_and_more'),
        ('products', '0035_remove_productinventory_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='Variant',
        ),
        migrations.RenameIndex(
            model_name='variant',
            new_name='products_va_product_502998_idx',
            old_name='products_pr_product_66459e_idx',
        ),
        migrations.RenameIndex(
            model_name='variant',
            new_name='products_va_stock_s_3439d4_idx',
            old_name='products_pr_stock_s_11b580_idx',
        ),
        migrations.AlterModelTable(
            name='variant',
            table='products_variant',
        ),
    ]
