# Generated by Django 4.2.16 on 2026-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_rename_variant_category_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variantinventory',
            name='unique_variant_inventory_location',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='variantinventory',
            name='batch_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='variantinventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantinventory',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variantinventory',
            name='shelf_location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='variantinventory',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expired', 'Expired'), ('damaged', 'Damaged')], default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='variantinventory',
            name='supplier',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('reserve', 'Reserve'), ('release', 'Release'), ('initial', 'Initial'), ('damaged', 'Damaged Stock'), ('expired', 'Expired Stock'), ('transfer', 'Transfer Between Branches'), ('supplier_return', 'Supplier Return'), ('customer_return', 'Customer Return')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='variantinventory',
            index=models.Index(fields=['variant', 'location', 'expiry_date'], name='products_va_variant_ccc520_idx'),
        ),
        migrations.AddIndex(
            model_name='variantinventory',
            index=models.Index(fields=['status', 'expiry_date'], name='products_va_status_567f08_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantinventory',
            constraint=models.UniqueConstraint(fields=('variant', 'location', 'batch_number'), name='unique_variant_inventory_location_batch'),
        ),
    ]
