# Generated by Django 4.2.16 on 2026-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_remove_variantinventory_unique_variant_inventory_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='authorized_supplier',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='variant',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_ppb_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_temperature_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='marketing_authorization_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='pil_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='variant',
            name='ppb_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='storage_instructions',
            field=models.TextField(blank=True),
        ),
    ]
