# Generated by Django 4.2.16 on 2026-07-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_variant_authorized_supplier_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'products_banner'
                              AND column_name = 'category_id'
                        ) THEN
                            ALTER TABLE "products_banner"
                            ADD COLUMN "category_id" bigint NULL;
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_class
                            WHERE relname = 'products_banner_category_id_6ffcde53'
                        ) THEN
                            CREATE INDEX "products_banner_category_id_6ffcde53"
                            ON "products_banner" ("category_id");
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'products_banner_category_id_6ffcde53_fk_prodcut_v'
                        ) THEN
                            ALTER TABLE "products_banner"
                            ADD CONSTRAINT "products_banner_category_id_6ffcde53_fk_prodcut_v"
                            FOREIGN KEY ("category_id")
                            REFERENCES "prodcut_variants_categories" ("id")
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    ALTER TABLE "products_banner"
                    DROP CONSTRAINT IF EXISTS "products_banner_category_id_6ffcde53_fk_prodcut_v";
                    DROP INDEX IF EXISTS "products_banner_category_id_6ffcde53";
                    ALTER TABLE "products_banner"
                    DROP COLUMN IF EXISTS "category_id";
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='banner',
                    name='category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.category'),
                ),
            ],
        ),
    ]
