# Generated by Django 4.2.16 on 2026-07-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_seed_ava_pharmacy_faqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.RemoveIndex(
            model_name='faq',
            name='products_fa_is_publ_74bcd2_idx',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='sort_order',
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_published', '-created_at'], name='products_fa_is_publ_f47208_idx'),
        ),
    ]
