# Generated by Django 4.2.16 on 2026-02-23 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('awaiting_sample', 'Awaiting Sample'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('result_ready', 'Result Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_sample', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority')], default='routine', max_length=20)),
                ('channel', models.CharField(choices=[('walk_in', 'Walk-in'), ('collection', 'Collection')], default='walk_in', max_length=20)),
                ('ordering_doctor', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('blood', 'Blood'), ('cardiac', 'Cardiac'), ('infectious', 'Infectious'), ('wellness', 'Wellness'), ('metabolic', 'Metabolic')], default='blood', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnaround', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('summary', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='lab/results/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('flags', models.JSONField(default=list)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab.labrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='lab.labtest'),
        ),
        migrations.CreateModel(
            name='LabAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='lab.labrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
