# Generated by Django 4.2.16 on 2026-03-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labpartner_labtechnicianprofile_labpartnerdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtechnicianprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='labpartner',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='background_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='compliance_declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='years_in_operation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='background_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='compliance_declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='license_board',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='license_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='payout_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='payout_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LabTechDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='lab_tech/documents/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('missing', 'Missing')], default='submitted', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lab.labtechnicianprofile')),
            ],
        ),
    ]
