# Generated by Django 4.2.16 on 2026-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_labtechnicianprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpartner',
            name='document_checklist',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='references',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='document_checklist',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='references',
            field=models.JSONField(default=list),
        ),
    ]
