# Generated by Django 4.2.16 on 2026-03-04 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0004_labpartner_document_checklist_labpartner_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpartner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_partner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
