# Generated by Django 4.2.16 on 2026-03-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0005_labpartner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpartner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='status_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='labpartner',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_technicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='status_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_technicians', to=settings.AUTH_USER_MODEL),
        ),
    ]
