# Generated by Django 4.2.16 on 2026-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_labpartner_created_at_labpartner_created_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labauditlog',
            index=models.Index(fields=['request', '-timestamp'], name='lab_labaudi_request_e4b0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='labpartner',
            index=models.Index(fields=['status', '-submitted_at'], name='lab_labpart_status_257323_idx'),
        ),
        migrations.AddIndex(
            model_name='labpartner',
            index=models.Index(fields=['user', 'status'], name='lab_labpart_user_id_f55c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['patient', 'status'], name='lab_labrequ_patient_f7fc9a_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['assigned_technician', 'status'], name='lab_labrequ_assigne_902a69_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['status', '-requested_at'], name='lab_labrequ_status_a851dc_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['payment_status', '-requested_at'], name='lab_labrequ_payment_8bb0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='labtechnicianprofile',
            index=models.Index(fields=['partner', 'status'], name='lab_labtech_partner_277afc_idx'),
        ),
        migrations.AddIndex(
            model_name='labtechnicianprofile',
            index=models.Index(fields=['user', 'status'], name='lab_labtech_user_id_426555_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['category', 'is_active'], name='lab_labtest_categor_cd0594_idx'),
        ),
    ]
