# Generated by Django 4.2.16 on 2026-08-31 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0007_labauditlog_lab_labaudi_request_e4b0cf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='assigned_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='lab.labpartner'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='assigned_pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_lab_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='collection_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='collection_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='result_delivery_method',
            field=models.CharField(choices=[('digital', 'Secure digital delivery'), ('physical_pickup', 'Physical result pickup')], default='digital', max_length=30),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='result_pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='channel',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('collection', 'Home sample collection')], default='collection', max_length=20),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['assigned_partner', 'status'], name='lab_labrequ_assigne_71de55_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['assigned_pharmacist', 'status'], name='lab_labrequ_assigne_b73aef_idx'),
        ),
    ]
