# Generated by Django 4.2.16 on 2026-08-31 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_legacy_facilities(apps, schema_editor):
    LabPartner = apps.get_model('lab', 'LabPartner')
    LabTest = apps.get_model('lab', 'LabTest')
    LabRequest = apps.get_model('lab', 'LabRequest')
    LabTechnicianProfile = apps.get_model('lab', 'LabTechnicianProfile')
    LaboratoryFacility = apps.get_model('lab', 'LaboratoryFacility')
    FacilityLabTest = apps.get_model('lab', 'FacilityLabTest')

    active_tests = list(LabTest.objects.filter(is_active=True))
    for partner in LabPartner.objects.all().iterator():
        status = partner.status if partner.status in ('verified', 'suspended') else 'pending'
        facility = LaboratoryFacility.objects.create(
            reference=f'LAB-F-{partner.pk:08X}',
            partner=partner,
            name=partner.location or 'Main Laboratory',
            email=partner.email,
            phone=partner.phone,
            county=partner.county,
            address=partner.address or partner.location,
            accreditation=partner.accreditation,
            license_number=partner.license_number or f'LEGACY-{partner.pk}',
            license_expiry=partner.license_expiry,
            supported_counties=[partner.county] if partner.county else [],
            home_collection_enabled=True,
            physical_result_pickup_enabled=True,
            status=status,
            verified_at=partner.verified_at,
        )
        facility.technicians.add(*LabTechnicianProfile.objects.filter(partner=partner))
        FacilityLabTest.objects.bulk_create([
            FacilityLabTest(
                facility=facility,
                test=test,
                price=test.price,
                turnaround=test.turnaround,
                home_collection_available=True,
            )
            for test in active_tests
        ])
        LabRequest.objects.filter(assigned_partner=partner).update(laboratory=facility)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0008_labrequest_assigned_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnaround', models.CharField(max_length=100)),
                ('home_collection_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['test__name'],
            },
        ),
        migrations.CreateModel(
            name='LaboratoryFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('accreditation', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('supported_counties', models.JSONField(default=list)),
                ('operating_hours', models.JSONField(default=dict)),
                ('home_collection_enabled', models.BooleanField(default=True)),
                ('physical_result_pickup_enabled', models.BooleanField(default=False)),
                ('pickup_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('status_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['partner__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='laboratoryfacility',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='lab.labpartner'),
        ),
        migrations.AddField(
            model_name='laboratoryfacility',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='lab.labtechnicianprofile'),
        ),
        migrations.AddField(
            model_name='laboratoryfacility',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_laboratory_facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitylabtest',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='lab.laboratoryfacility'),
        ),
        migrations.AddField(
            model_name='facilitylabtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_offerings', to='lab.labtest'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='lab.laboratoryfacility'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['laboratory', 'status'], name='lab_labrequ_laborat_d1ce2a_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryfacility',
            index=models.Index(fields=['partner', 'status', 'is_active'], name='lab_laborat_partner_6d6edc_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryfacility',
            index=models.Index(fields=['county', 'status', 'is_active'], name='lab_laborat_county_4992a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='laboratoryfacility',
            constraint=models.UniqueConstraint(fields=('partner', 'name'), name='unique_partner_facility_name'),
        ),
        migrations.AddIndex(
            model_name='facilitylabtest',
            index=models.Index(fields=['facility', 'is_active'], name='lab_facilit_facilit_dfe62b_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitylabtest',
            index=models.Index(fields=['test', 'is_active'], name='lab_facilit_test_id_006efa_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilitylabtest',
            constraint=models.UniqueConstraint(fields=('facility', 'test'), name='unique_facility_lab_test'),
        ),
        migrations.RunPython(create_legacy_facilities, noop_reverse),
    ]
