# Generated by Django 4.2.16 on 2026-08-31 12:04

from django.db import migrations, models
import django.db.models.deletion


def copy_legacy_partner_documents(apps, schema_editor):
    LabPartnerDocument = apps.get_model('lab', 'LabPartnerDocument')
    LaboratoryFacility = apps.get_model('lab', 'LaboratoryFacility')
    LaboratoryFacilityDocument = apps.get_model('lab', 'LaboratoryFacilityDocument')
    for document in LabPartnerDocument.objects.exclude(file='').iterator():
        facility = LaboratoryFacility.objects.filter(partner_id=document.partner_id).first()
        if facility:
            LaboratoryFacilityDocument.objects.create(
                facility=facility,
                name=document.name,
                file=document.file.name,
                status='verified' if facility.status == 'verified' else 'submitted',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_facilitylabtest_laboratoryfacility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryFacilityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='laboratory_facilities/documents/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lab.laboratoryfacility')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RunPython(copy_legacy_partner_documents, migrations.RunPython.noop),
    ]
