# Generated by Django 4.2.16 on 2026-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payoutrule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['recipient', 'status'], name='payouts_pay_recipie_a657d3_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['role', 'status'], name='payouts_pay_role_58a431_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', '-requested_at'], name='payouts_pay_status_cb2411_idx'),
        ),
    ]
