# Generated by Django 4.2.16 on 2026-07-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_payout_payouts_pay_recipie_a657d3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('pediatrician', 'Pediatrician'), ('pharmacist', 'Pharmacist'), ('lab_partner', 'Lab Partner'), ('lab_technician', 'Lab Technician')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutrule',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('pediatrician', 'Pediatrician'), ('pharmacist', 'Pharmacist'), ('lab_partner', 'Lab Partner'), ('lab_technician', 'Lab Technician')], max_length=20, unique=True),
        ),
    ]
