# Generated by Django 4.2.16 on 2026-07-17 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_gross_amount(apps, schema_editor):
    Payout = apps.get_model('payouts', 'Payout')
    for payout in Payout.objects.filter(gross_amount=0).iterator():
        payout.gross_amount = payout.amount
        payout.save(update_fields=['gross_amount'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payouts', '0004_alter_payout_role_alter_payoutrule_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payout',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='batch_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payout',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='payout',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payout',
            name='failure_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='payout',
            name='failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payout',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payout',
            name='reconciliation_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('exception', 'Exception')], default='unmatched', max_length=20),
        ),
        migrations.AddField(
            model_name='payout',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='source_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payout',
            name='source_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payout',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='withholding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_gross_amount, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('on_hold', 'On Hold'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['source_type', 'source_reference'], name='payouts_pay_source__cb59b8_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['reconciliation_status', '-requested_at'], name='payouts_pay_reconci_35db10_idx'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference', ''), _negated=True), fields=('recipient', 'role', 'source_type', 'source_reference'), name='unique_payout_source_per_recipient'),
        ),
        migrations.AddField(
            model_name='payoutauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutauditlog',
            name='payout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='payouts.payout'),
        ),
        migrations.AddIndex(
            model_name='payoutauditlog',
            index=models.Index(fields=['payout', '-created_at'], name='payouts_pay_payout__cd02eb_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutauditlog',
            index=models.Index(fields=['action', '-created_at'], name='payouts_pay_action_af5f63_idx'),
        ),
    ]
