# Generated by Django 4.2.16 on 2026-07-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0005_payoutauditlog_payout_approved_at_payout_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('provider_transaction_id',), name='unique_payout_provider_transaction'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_reference', ''), _negated=True), fields=('payment_reference',), name='unique_payout_payment_reference'),
        ),
    ]
