# Generated by Django 4.2.16 on 2026-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='background_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='compliance_declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consult_modes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_board',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='payout_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='payout_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='references',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
