# Generated by Django 4.2.16 on 2026-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_doctorprofile_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='document_checklist',
            field=models.JSONField(default=list),
        ),
    ]
