# Generated by Django 4.2.16 on 2026-03-04 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0003_doctorprofile_bio_doctorprofile_document_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='type',
            field=models.CharField(choices=[('doctor', 'Doctor')], default='doctor', max_length=20),
        ),
        migrations.CreateModel(
            name='PediatricianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=100)),
                ('license_board', models.CharField(blank=True, max_length=200)),
                ('license_country', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.JSONField(default=list)),
                ('consult_modes', models.JSONField(default=list)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('references', models.JSONField(default=list)),
                ('document_checklist', models.JSONField(default=list)),
                ('payout_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=20)),
                ('payout_account', models.CharField(blank=True, max_length=100)),
                ('background_consent', models.BooleanField(default=False)),
                ('compliance_declaration', models.BooleanField(default=False)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('status_note', models.TextField(blank=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('consult_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pediatrician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PediatricianDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='pediatricians/documents/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('missing', 'Missing')], default='submitted', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pediatrician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='consultations.pediatricianprofile')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='pediatrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.pediatricianprofile'),
        ),
        migrations.AlterField(
            model_name='doctorearning',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='consultations.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorearning',
            name='pediatrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='consultations.pediatricianprofile'),
        ),
        migrations.AddField(
            model_name='doctorprescription',
            name='pediatrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_prescriptions', to='consultations.pediatricianprofile'),
        ),
    ]
