# Generated by Django 4.2.16 on 2026-03-04 17:54

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    DoctorPrescription = apps.get_model('consultations', 'DoctorPrescription')
    PediatricianPrescription = apps.get_model('consultations', 'PediatricianPrescription')
    DoctorEarning = apps.get_model('consultations', 'DoctorEarning')
    PediatricianEarning = apps.get_model('consultations', 'PediatricianEarning')

    for row in DoctorPrescription.objects.exclude(pediatrician_id=None):
        created = PediatricianPrescription.objects.create(
            reference=row.reference,
            pediatrician_id=row.pediatrician_id,
            consultation_id=row.consultation_id,
            patient_name=row.patient_name,
            items=row.items,
            status=row.status,
            notes=row.notes,
        )
        if row.created_at:
            PediatricianPrescription.objects.filter(pk=created.pk).update(created_at=row.created_at)
        row.delete()

    for row in DoctorEarning.objects.exclude(pediatrician_id=None):
        created = PediatricianEarning.objects.create(
            pediatrician_id=row.pediatrician_id,
            consultation_id=row.consultation_id,
            amount=row.amount,
            description=row.description,
        )
        if row.earned_at:
            PediatricianEarning.objects.filter(pk=created.pk).update(earned_at=row.earned_at)
        row.delete()


def backwards(apps, schema_editor):
    DoctorPrescription = apps.get_model('consultations', 'DoctorPrescription')
    PediatricianPrescription = apps.get_model('consultations', 'PediatricianPrescription')
    DoctorEarning = apps.get_model('consultations', 'DoctorEarning')
    PediatricianEarning = apps.get_model('consultations', 'PediatricianEarning')

    for row in PediatricianPrescription.objects.all():
        restored = DoctorPrescription.objects.create(
            reference=row.reference,
            doctor_id=None,
            pediatrician_id=row.pediatrician_id,
            consultation_id=row.consultation_id,
            patient_name=row.patient_name,
            items=row.items,
            status=row.status,
            notes=row.notes,
        )
        if row.created_at:
            DoctorPrescription.objects.filter(pk=restored.pk).update(created_at=row.created_at)
        row.delete()

    for row in PediatricianEarning.objects.all():
        restored = DoctorEarning.objects.create(
            doctor_id=None,
            pediatrician_id=row.pediatrician_id,
            consultation_id=row.consultation_id,
            amount=row.amount,
            description=row.description,
        )
        if row.earned_at:
            DoctorEarning.objects.filter(pk=restored.pk).update(earned_at=row.earned_at)
        row.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_split_pediatricians_from_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PediatricianPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('dispensed', 'Dispensed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pediatrician_prescriptions', to='consultations.consultation')),
                ('pediatrician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_prescriptions', to='consultations.pediatricianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PediatricianEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation')),
                ('pediatrician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='consultations.pediatricianprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='doctorearning',
            name='pediatrician',
        ),
        migrations.RemoveField(
            model_name='doctorprescription',
            name='pediatrician',
        ),
    ]
