# Generated by Django 4.2.16 on 2026-03-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0006_remove_doctorearning_pediatrician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doctor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_doctor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pediatricianprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pediatricianprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pediatrician_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pediatricianprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pediatrician_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
