# Generated by Django 4.2.16 on 2026-03-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_doctorprofile_created_at_doctorprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pediatricianprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
