# Generated by Django 4.2.16 on 2026-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_doctorprofile_address_pediatricianprofile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pediatricianprescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'status'], name='consultatio_patient_a614a6_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor', 'status'], name='consultatio_doctor__41a060_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['pediatrician', 'status'], name='consultatio_pediatr_6133fb_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status', '-created_at'], name='consultatio_status_49d4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['is_pediatric', 'status'], name='consultatio_is_pedi_b5821a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationmessage',
            index=models.Index(fields=['consultation', 'sent_at'], name='consultatio_consult_48bb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorearning',
            index=models.Index(fields=['doctor', '-earned_at'], name='consultatio_doctor__6f1b11_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprescription',
            index=models.Index(fields=['doctor', 'status'], name='consultatio_doctor__83ee09_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprescription',
            index=models.Index(fields=['consultation', 'status'], name='consultatio_consult_536820_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['status', '-submitted_at'], name='consultatio_status_425851_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['user', 'status'], name='consultatio_user_id_347ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='pediatricianearning',
            index=models.Index(fields=['pediatrician', '-earned_at'], name='consultatio_pediatr_2bf010_idx'),
        ),
        migrations.AddIndex(
            model_name='pediatricianprescription',
            index=models.Index(fields=['pediatrician', 'status'], name='consultatio_pediatr_e571fe_idx'),
        ),
        migrations.AddIndex(
            model_name='pediatricianprescription',
            index=models.Index(fields=['consultation', 'status'], name='consultatio_consult_9c0e30_idx'),
        ),
        migrations.AddIndex(
            model_name='pediatricianprofile',
            index=models.Index(fields=['status', '-submitted_at'], name='consultatio_status_a5cb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='pediatricianprofile',
            index=models.Index(fields=['user', 'status'], name='consultatio_user_id_db5bdf_idx'),
        ),
    ]
