# Generated by Django 4.2.16 on 2026-03-17 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_unified_clinicians(apps, schema_editor):
    DoctorProfile = apps.get_model('consultations', 'DoctorProfile')
    PediatricianProfile = apps.get_model('consultations', 'PediatricianProfile')
    DoctorDocument = apps.get_model('consultations', 'DoctorDocument')
    PediatricianDocument = apps.get_model('consultations', 'PediatricianDocument')
    DoctorPrescription = apps.get_model('consultations', 'DoctorPrescription')
    PediatricianPrescription = apps.get_model('consultations', 'PediatricianPrescription')
    DoctorEarning = apps.get_model('consultations', 'DoctorEarning')
    PediatricianEarning = apps.get_model('consultations', 'PediatricianEarning')
    ClinicianProfile = apps.get_model('consultations', 'ClinicianProfile')
    ClinicianDocument = apps.get_model('consultations', 'ClinicianDocument')
    ClinicianPrescription = apps.get_model('consultations', 'ClinicianPrescription')
    ClinicianEarning = apps.get_model('consultations', 'ClinicianEarning')
    Consultation = apps.get_model('consultations', 'Consultation')

    doctor_map = {}
    pediatrician_map = {}

    for legacy in DoctorProfile.objects.all():
        clinician, _ = ClinicianProfile.objects.get_or_create(
            legacy_doctor_id=legacy.id,
            defaults={
                'provider_type': 'doctor',
                'reference': legacy.reference,
                'user_id': legacy.user_id,
                'name': legacy.name,
                'specialty': legacy.specialty,
                'email': legacy.email,
                'phone': legacy.phone,
                'license_number': legacy.license_number,
                'license_board': legacy.license_board,
                'license_country': legacy.license_country,
                'license_expiry': legacy.license_expiry,
                'id_number': legacy.id_number,
                'facility': legacy.facility,
                'availability': legacy.availability,
                'bio': legacy.bio,
                'languages': legacy.languages,
                'consult_modes': legacy.consult_modes,
                'years_experience': legacy.years_experience,
                'county': legacy.county,
                'address': legacy.address,
                'references': legacy.references,
                'document_checklist': legacy.document_checklist,
                'payout_method': legacy.payout_method,
                'payout_account': legacy.payout_account,
                'background_consent': legacy.background_consent,
                'compliance_declaration': legacy.compliance_declaration,
                'agreed_to_terms': legacy.agreed_to_terms,
                'status': legacy.status,
                'status_note': legacy.status_note,
                'rejection_note': legacy.rejection_note,
                'commission': legacy.commission,
                'consult_fee': legacy.consult_fee,
                'rating': legacy.rating,
                'verified_at': legacy.verified_at,
                'created_by_id': legacy.created_by_id,
                'updated_by_id': legacy.updated_by_id,
            },
        )
        ClinicianProfile.objects.filter(pk=clinician.pk).update(
            submitted_at=legacy.submitted_at,
            created_at=legacy.created_at,
            updated_at=legacy.updated_at,
        )
        doctor_map[legacy.id] = clinician.id

    for legacy in PediatricianProfile.objects.all():
        clinician, _ = ClinicianProfile.objects.get_or_create(
            legacy_pediatrician_id=legacy.id,
            defaults={
                'provider_type': 'pediatrician',
                'reference': legacy.reference,
                'user_id': legacy.user_id,
                'name': legacy.name,
                'specialty': legacy.specialty,
                'email': legacy.email,
                'phone': legacy.phone,
                'license_number': legacy.license_number,
                'license_board': legacy.license_board,
                'license_country': legacy.license_country,
                'license_expiry': legacy.license_expiry,
                'id_number': legacy.id_number,
                'facility': legacy.facility,
                'availability': legacy.availability,
                'bio': legacy.bio,
                'languages': legacy.languages,
                'consult_modes': legacy.consult_modes,
                'years_experience': legacy.years_experience,
                'county': legacy.county,
                'address': legacy.address,
                'references': legacy.references,
                'document_checklist': legacy.document_checklist,
                'payout_method': legacy.payout_method,
                'payout_account': legacy.payout_account,
                'background_consent': legacy.background_consent,
                'compliance_declaration': legacy.compliance_declaration,
                'agreed_to_terms': legacy.agreed_to_terms,
                'status': legacy.status,
                'status_note': legacy.status_note,
                'rejection_note': legacy.rejection_note,
                'commission': legacy.commission,
                'consult_fee': legacy.consult_fee,
                'rating': legacy.rating,
                'verified_at': legacy.verified_at,
                'created_by_id': legacy.created_by_id,
                'updated_by_id': legacy.updated_by_id,
            },
        )
        ClinicianProfile.objects.filter(pk=clinician.pk).update(
            submitted_at=legacy.submitted_at,
            created_at=legacy.created_at,
            updated_at=legacy.updated_at,
        )
        pediatrician_map[legacy.id] = clinician.id

    for document in DoctorDocument.objects.all():
        clinician_id = doctor_map.get(document.doctor_id)
        if not clinician_id:
            continue
        created = ClinicianDocument.objects.create(
            clinician_id=clinician_id,
            name=document.name,
            file=document.file,
            status=document.status,
            note=document.note,
        )
        ClinicianDocument.objects.filter(pk=created.pk).update(uploaded_at=document.uploaded_at)

    for document in PediatricianDocument.objects.all():
        clinician_id = pediatrician_map.get(document.pediatrician_id)
        if not clinician_id:
            continue
        created = ClinicianDocument.objects.create(
            clinician_id=clinician_id,
            name=document.name,
            file=document.file,
            status=document.status,
            note=document.note,
        )
        ClinicianDocument.objects.filter(pk=created.pk).update(uploaded_at=document.uploaded_at)

    for consultation in Consultation.objects.all():
        clinician_id = None
        if consultation.doctor_id:
            clinician_id = doctor_map.get(consultation.doctor_id)
        elif consultation.pediatrician_id:
            clinician_id = pediatrician_map.get(consultation.pediatrician_id)
        if clinician_id and consultation.clinician_id != clinician_id:
            consultation.clinician_id = clinician_id
            consultation.save(update_fields=['clinician'])

    for prescription in DoctorPrescription.objects.all():
        clinician_id = doctor_map.get(prescription.doctor_id)
        if not clinician_id:
            continue
        created = ClinicianPrescription.objects.create(
            clinician_id=clinician_id,
            consultation_id=prescription.consultation_id,
            patient_name=prescription.patient_name,
            items=prescription.items,
            status=prescription.status,
            notes=prescription.notes,
            reference=prescription.reference,
        )
        ClinicianPrescription.objects.filter(pk=created.pk).update(created_at=prescription.created_at)

    for prescription in PediatricianPrescription.objects.all():
        clinician_id = pediatrician_map.get(prescription.pediatrician_id)
        if not clinician_id:
            continue
        created = ClinicianPrescription.objects.create(
            clinician_id=clinician_id,
            consultation_id=prescription.consultation_id,
            patient_name=prescription.patient_name,
            items=prescription.items,
            status=prescription.status,
            notes=prescription.notes,
            reference=prescription.reference,
        )
        ClinicianPrescription.objects.filter(pk=created.pk).update(created_at=prescription.created_at)

    for earning in DoctorEarning.objects.all():
        clinician_id = doctor_map.get(earning.doctor_id)
        if not clinician_id:
            continue
        created = ClinicianEarning.objects.create(
            clinician_id=clinician_id,
            consultation_id=earning.consultation_id,
            amount=earning.amount,
            description=earning.description,
        )
        ClinicianEarning.objects.filter(pk=created.pk).update(earned_at=earning.earned_at)

    for earning in PediatricianEarning.objects.all():
        clinician_id = pediatrician_map.get(earning.pediatrician_id)
        if not clinician_id:
            continue
        created = ClinicianEarning.objects.create(
            clinician_id=clinician_id,
            consultation_id=earning.consultation_id,
            amount=earning.amount,
            description=earning.description,
        )
        ClinicianEarning.objects.filter(pk=created.pk).update(earned_at=earning.earned_at)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0009_alter_doctorprescription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='doctors/documents/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('missing', 'Missing')], default='submitted', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicianEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicianPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('dispensed', 'Dispensed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=100)),
                ('license_board', models.CharField(blank=True, max_length=200)),
                ('license_country', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('languages', models.JSONField(default=list)),
                ('consult_modes', models.JSONField(default=list)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('references', models.JSONField(default=list)),
                ('document_checklist', models.JSONField(default=list)),
                ('payout_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=20)),
                ('payout_account', models.CharField(blank=True, max_length=100)),
                ('background_consent', models.BooleanField(default=False)),
                ('compliance_declaration', models.BooleanField(default=False)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('status_note', models.TextField(blank=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('consult_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('doctor', 'Doctor'), ('pediatrician', 'Pediatrician')], max_length=20)),
                ('legacy_doctor_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('legacy_pediatrician_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinician_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clinician_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicianprescription',
            name='clinician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_prescriptions', to='consultations.clinicianprofile'),
        ),
        migrations.AddField(
            model_name='clinicianprescription',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinician_prescriptions', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='clinicianearning',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='consultations.clinicianprofile'),
        ),
        migrations.AddField(
            model_name='clinicianearning',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='cliniciandocument',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='consultations.clinicianprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='clinician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.clinicianprofile'),
        ),
        migrations.RunPython(backfill_unified_clinicians, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['clinician', 'status'], name='consultatio_clinici_c3d5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicianprofile',
            index=models.Index(fields=['provider_type', 'status'], name='consultatio_provide_b8a326_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicianprofile',
            index=models.Index(fields=['status', '-submitted_at'], name='consultatio_status_521114_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicianprofile',
            index=models.Index(fields=['user', 'status'], name='consultatio_user_id_c4d683_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicianprescription',
            index=models.Index(fields=['clinician', 'status'], name='consultatio_clinici_485237_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicianprescription',
            index=models.Index(fields=['consultation', 'status'], name='consultatio_consult_325f08_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicianearning',
            index=models.Index(fields=['clinician', '-earned_at'], name='consultatio_clinici_c5f11e_idx'),
        ),
    ]
