# Generated by Django 4.2.16 on 2026-03-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_cliniciandocument_clinicianearning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordocument',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorearning',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='doctorearning',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorprescription',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='doctorprescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pediatriciandocument',
            name='pediatrician',
        ),
        migrations.RemoveField(
            model_name='pediatricianearning',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='pediatricianearning',
            name='pediatrician',
        ),
        migrations.RemoveField(
            model_name='pediatricianprescription',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='pediatricianprescription',
            name='pediatrician',
        ),
        migrations.RemoveField(
            model_name='pediatricianprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pediatricianprofile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pediatricianprofile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='consultation',
            name='consultatio_doctor__41a060_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultation',
            name='consultatio_pediatr_6133fb_idx',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='pediatrician',
        ),
        migrations.DeleteModel(
            name='DoctorDocument',
        ),
        migrations.DeleteModel(
            name='DoctorEarning',
        ),
        migrations.DeleteModel(
            name='DoctorPrescription',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='PediatricianDocument',
        ),
        migrations.DeleteModel(
            name='PediatricianEarning',
        ),
        migrations.DeleteModel(
            name='PediatricianPrescription',
        ),
        migrations.DeleteModel(
            name='PediatricianProfile',
        ),
    ]
