# Generated by Django 4.2.16 on 2026-03-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_remove_doctordocument_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
