# Generated by Django 4.2.16 on 2026-03-23 17:53

import avapharmacy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_remove_doctordocument_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianprescription',
            name='digital_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinicianprescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicianprescription',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='payout_account_number',
            field=avapharmacy.fields.OptionalEncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='consultations/messages/'),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('e_prescription', 'E-Prescription')], default='text', max_length=20),
        ),
    ]
