# Generated by Django 4.2.16 on 2026-06-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0013_clinicianprescription_digital_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('approved_pending_activation', 'Approved - Pending Activation'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='ConsultationPaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa STK Push'), ('paybill', 'M-Pesa Paybill')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requires_action', 'Requires Action'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, max_length=120)),
                ('checkout_request_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('consultation_payload', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_payment_intents', to='consultations.clinicianprofile')),
                ('consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intent', to='consultations.consultation')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['initiated_by', 'status'], name='consultatio_initiat_0c78fe_idx'), models.Index(fields=['provider', 'status'], name='consultatio_provide_69a523_idx'), models.Index(fields=['checkout_request_id'], name='consultatio_checkou_e6c1d7_idx'), models.Index(fields=['external_reference'], name='consultatio_externa_9310b2_idx')],
            },
        ),
    ]
