# Generated by Django 4.2.16 on 2026-06-15 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0015_consultationauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
