# Generated by Django 4.2.16 on 2026-06-21 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0017_consultation_requested_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_years', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('chronic_conditions', models.JSONField(blank=True, default=list)),
                ('current_medications', models.JSONField(blank=True, default=list)),
                ('vaccination_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='child_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consultation',
            name='child_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.childpatient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='guardian_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['child_patient', 'status'], name='consultatio_child_p_5537a0_idx'),
        ),
        migrations.AddIndex(
            model_name='childpatient',
            index=models.Index(fields=['guardian', 'is_active'], name='consultatio_guardia_00c9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='childpatient',
            index=models.Index(fields=['reference'], name='consultatio_referen_887570_idx'),
        ),
    ]
