# Generated by Django 4.2.16 on 2026-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_unique_non_empty_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('pharmacist', 'Pharmacist'), ('doctor', 'Doctor'), ('pediatrician', 'Pediatrician'), ('lab_partner', 'Lab Partner'), ('lab_technician', 'Lab Technician'), ('inventory_staff', 'Inventory Staff')], default='customer', max_length=20),
        ),
    ]
