# Generated by Django 4.2.16 on 2026-03-05 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PharmacistProfile',
            new_name='Pharmacist',
        ),
        migrations.AlterModelTable(
            name='pharmacist',
            table='accounts_pharmacist',
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist', to=settings.AUTH_USER_MODEL),
        ),
    ]
