# Generated by Django 4.2.16 on 2026-03-05 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pharmacist_delete_pharmacistprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacistActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sent_to', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pharmacist_activation_tokens', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_activation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_pharmacist_activation_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='accounts_ph_user_id_249d1e_idx'), models.Index(fields=['user', 'used_at'], name='accounts_ph_user_id_692534_idx')],
            },
        ),
    ]
