# Generated by Django 4.2.16 on 2026-03-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def backfill_customer_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Customer = apps.get_model('accounts', 'Customer')
    now = timezone.now()

    existing_user_ids = set(Customer.objects.values_list('user_id', flat=True))
    rows = []
    for user in User.objects.filter(role='customer').only('id'):
        if user.id in existing_user_ids:
            continue
        rows.append(Customer(user_id=user.id, created_at=now, updated_at=now))
    if rows:
        Customer.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pharmacistactivationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pharmacists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pharmacists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_customer',
            },
        ),
        migrations.RunPython(backfill_customer_profiles, migrations.RunPython.noop),
    ]
