# Generated by Django 4.2.16 on 2026-03-05 12:04

from django.db import migrations
from django.utils import timezone


def backfill_customer_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Customer = apps.get_model('accounts', 'Customer')
    now = timezone.now()

    existing_user_ids = set(Customer.objects.values_list('user_id', flat=True))
    rows = []
    for user in User.objects.filter(role='customer').only('id'):
        if user.id in existing_user_ids:
            continue
        rows.append(Customer(user_id=user.id, created_at=now, updated_at=now))
    if rows:
        Customer.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pharmacist_created_at_pharmacist_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_customer_profiles, migrations.RunPython.noop),
    ]
