# Generated by Django 4.2.16 on 2026-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backfill_customer_profiles'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='accounts_ad_user_id_c8244c_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', '-created_at'], name='accounts_ad_user_id_cae8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='accounts_ad_actor_i_5e2a26_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action', '-created_at'], name='accounts_ad_action_e8d30c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='accounts_ad_entity__3a69da_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='accounts_us_role_9fc6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'date_joined'], name='accounts_us_status_2e3176_idx'),
        ),
        migrations.AddIndex(
            model_name='usernote',
            index=models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_fd97cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
    ]
