# Generated by Django 4.2.16 on 2026-03-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_address_accounts_ad_user_id_c8244c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('support_email', models.EmailField(default='support@avapharmacy.co.ke', max_length=254)),
                ('support_phone', models.CharField(default='+254 700 000 000', max_length=20)),
                ('whatsapp_phone', models.CharField(default='+254 700 000 000', max_length=20)),
                ('support_address', models.CharField(default='Karen / The Hub, Karen, Nairobi, Kenya', max_length=255)),
                ('support_hours', models.CharField(default='Mon – Sun: 09am – 5pm', max_length=255)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('active_delivery_zones', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
                'db_table': 'accounts_site_settings',
            },
        ),
    ]
