# Generated by Django 4.2.16 on 2026-06-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='branch_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='pharmacist',
            index=models.Index(fields=['license_number'], name='accounts_ph_license_30daae_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacist',
            index=models.Index(fields=['branch_location'], name='accounts_ph_branch__0fb150_idx'),
        ),
    ]
