# Generated by Django 4.2.16 on 2026-06-10 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_pharmacist_branch_location_pharmacist_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_verification', 'Pending Verification'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerEmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sent_to', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_customer_email_verification_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='accounts_cu_user_id_bfc43b_idx'), models.Index(fields=['user', 'used_at'], name='accounts_cu_user_id_b6f1ea_idx')],
            },
        ),
    ]
