# Generated by Django 4.2.16 on 2026-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_gender_alter_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('pharmacist', 'Pharmacist'), ('doctor', 'Doctor'), ('pediatrician', 'Pediatrician'), ('lab_partner', 'Lab Partner'), ('lab_technician', 'Lab Technician'), ('inventory_staff', 'Inventory Staff'), ('ppb_inspector', 'PPB Inspector')], default='customer', max_length=20),
        ),
    ]
