# Generated by Django 4.2.16 on 2026-07-03 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('forgot_password', 'Forgot password'), ('checkout', 'Checkout'), ('prescription_upload', 'Prescription upload'), ('challenge_failed', 'Challenge failed'), ('honeypot', 'Honeypot')], max_length=40)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('challenge', 'Challenge'), ('verify', 'Verify account'), ('block', 'Block'), ('review', 'Manual review')], default='allow', max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_risk_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_bot_risk_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='accounts_bo_event_t_3e921e_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_bo_ip_addr_87b0de_idx'), models.Index(fields=['user', '-created_at'], name='accounts_bo_user_id_71490b_idx'), models.Index(fields=['device_id', '-created_at'], name='accounts_bo_device__64170e_idx'), models.Index(fields=['decision', '-created_at'], name='accounts_bo_decisio_ff2908_idx')],
            },
        ),
    ]
