# Generated by Django 4.2.16 on 2026-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supportnote',
            index=models.Index(fields=['ticket', 'created_at'], name='support_sup_ticket__99ebd0_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['customer', 'status'], name='support_sup_custome_c8c9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_sup_assigne_87974a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='support_sup_status_9e6ce4_idx'),
        ),
    ]
