# Generated by Django 4.2.16 on 2026-03-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportnote_support_sup_ticket__99ebd0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(blank=True, default='website', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['email'], name='support_new_email_4e6b95_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['is_active', '-subscribed_at'], name='support_new_is_acti_9b5f3a_idx'),
        ),
    ]
