# Generated by Django 4.2.16 on 2026-07-03 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='complaint_policy_url',
            field=models.CharField(default='/help', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='health_safety_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='online_pharmacy_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pharmacist_consultation_hours',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ppb_contact_address',
            field=models.CharField(default='Lenana Road Opposite Russian Embassy, P. O. Box 27663-00506, Nairobi, Kenya', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ppb_contact_email',
            field=models.EmailField(default='info@pharmacyboardkenya.org.ke', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ppb_contact_name',
            field=models.CharField(default='The Pharmacy and Poisons Board', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ppb_contact_phone',
            field=models.CharField(default='+254 709 770 100', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ppb_website',
            field=models.URLField(default='https://www.pharmacyboardkenya.org.ke'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='premises_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_url',
            field=models.CharField(default='/privacy', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='returns_policy_url',
            field=models.CharField(default='/returns', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='superintendent_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='superintendent_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('odpc_certificate', 'ODPC certificate'), ('data_center_proof', 'Kenya data-center proof'), ('x509_certificate', 'X.509 / SSL certificate'), ('third_party_sla', 'Third-party SLA'), ('backup_evidence', 'Backup evidence'), ('iso27001_control', 'ISO/IEC 27001 control evidence'), ('ppb_authorization', 'PPB authorization'), ('qa_audit_report', 'QA audit report')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('issuing_authority', models.CharField(blank=True, max_length=160)),
                ('file', models.FileField(blank=True, upload_to='compliance/evidence/')),
                ('external_url', models.URLField(blank=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review_due', 'Review due'), ('expired', 'Expired')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_evidence', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_compliance_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['evidence_type', 'expires_at', 'title'],
                'indexes': [models.Index(fields=['evidence_type', 'status'], name='support_com_evidenc_8c45c5_idx'), models.Index(fields=['expires_at'], name='support_com_expires_165701_idx')],
            },
        ),
    ]
