# Generated by Django 4.2.16 on 2026-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescriptionitem_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_283c70_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', '-submitted_at'], name='prescriptio_status_1cc36f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['dispatch_status', '-submitted_at'], name='prescriptio_dispatc_e544ff_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionauditlog',
            index=models.Index(fields=['prescription', '-timestamp'], name='prescriptio_prescri_f3b238_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionfile',
            index=models.Index(fields=['prescription', '-uploaded_at'], name='prescriptio_prescri_fd833d_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription', 'product'], name='prescriptio_prescri_2c0d61_idx'),
        ),
    ]
