# Generated by Django 4.2.16 on 2026-03-23 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_clinicianprescription_digital_signature_and_more'),
        ('prescriptions', '0003_prescription_prescriptio_patient_283c70_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='clarification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='clinician_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_prescriptions', to='consultations.clinicianprescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('e_prescription', 'E-Prescription')], default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionauditlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='is_controlled_substance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['source', 'status'], name='prescriptio_source_826fe8_idx'),
        ),
    ]
