# Generated by Django 4.2.16 on 2026-03-28 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_clarification_messages(apps, schema_editor):
    Prescription = apps.get_model('prescriptions', 'Prescription')
    PrescriptionClarificationMessage = apps.get_model('prescriptions', 'PrescriptionClarificationMessage')

    rows = []
    for prescription in Prescription.objects.exclude(clarification_message='').iterator():
        rows.append(
            PrescriptionClarificationMessage(
                prescription_id=prescription.id,
                sender_id=prescription.pharmacist_id,
                sender_role='pharmacist' if prescription.pharmacist_id else 'system',
                sender_name='',
                message=prescription.clarification_message,
            )
        )
    if rows:
        PrescriptionClarificationMessage.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0004_prescription_clarification_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionClarificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_messages', to='prescriptions.prescription')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_clarification_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['prescription', 'created_at'], name='prescriptio_prescri_8da0e0_idx'), models.Index(fields=['sender_role', 'created_at'], name='prescriptio_sender__74435e_idx')],
            },
        ),
        migrations.RunPython(backfill_clarification_messages, migrations.RunPython.noop),
    ]
