# Generated by Django 4.2.16 on 2026-06-05 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_rename_variant_category_indexes'),
        ('prescriptions', '0006_prescriptionreviewdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='products.variant'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription', 'variant'], name='prescriptio_prescri_c11657_idx'),
        ),
    ]
