# Generated by Django 4.2.16 on 2026-07-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_prescriptionitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity_measurement',
            field=models.CharField(blank=True, default='unit(s)', max_length=60),
        ),
    ]
